<article id="about" class="page">
    <p class="para">
        A passionate programmer, web designer, security researcher and a network guy. I entered to the field of Information Technology <?php echo date("Y") - 2010; ?> years ago (in 2010) as a <a href="https://en.wikipedia.org/wiki/Programmer">Programmer</a> with little knowledge in <a href="https://en.wikipedia.org/wiki/Disk_operating_system">DOS</a> Programming but a lot of enthusiastic to become a profressional programmer.
        My first attempt was to learn a proper language was to learn <a href="https://en.wikipedia.org/wiki/Visual_Basic">Visual Basics</a>. So i learnt VB, did some researches and did some projects and i felt that this is not bad. I kept learning other programming languages including <a href="https://en.wikipedia.org/wiki/Java_(programming_language)">Java</a>, <a href="https://en.wikipedia.org/wiki/C_(programming_language)">C</a>, <a href="https://en.wikipedia.org/wiki/C%2B%2B">C++</a>
        and then wanted to learn web designing. As a start i learnt basic <a href="https://en.wikipedia.org/wiki/HTML">HTML</a>, <a href="https://en.wikipedia.org/wiki/PHP">PHP</a> and <a href="https://en.wikipedia.org/wiki/Cascading_Style_Sheets">CSS</a> but didn't want to go deep into the subject since i felt in love with Desktop Application Programming.
    </p>
    <p class="para">
        Then i started following <a href="http://www.bcs.org/category/18011">BCS Higher Education Qualification</a> to get some degree in the field. As i learnt "Computer Network Technology" for BCS, my lecturer was <a href="https://www.facebook.com/milan.maduranga">Mr.Milan Maduranga</a> who influenced me to learn Networking. That was when i started learning Networking as a student of him and then as a student of <a href="https://www.facebook.com/tharaka.guruge.7">Mr.Tharaka Guruge</a> when
        i was following <a href="http://www.cisco.com/web/learning/certifications/associate/ccna/index.html">CCNA</a> in <a href="https://en.wikipedia.org/wiki/Cisco_Networking_Academy">Cisco Network Academy</a>.I got my first professional certification which was CCNA and then started learning for <a href="http://www.cisco.com/web/learning/certifications/associate/ccna_security/index.html">CCNA Security</a>. I wanted to learn Network security since i always loved to hack things and that thing which is "Ethical Hacker" became my new 
        goal. i had a little knowledge of the concept IT Security, but i wanted to master it, and actually i didn't satisfy with those poor script kiddie things. So i learnt CCNA Security and learnt a lot in Networking Security and got title as a "CCNA Security".
    </p>
    <p class="para">
        I was working in some companies, specially in Networking field and i lot focused Networking Security and Cyber Security. One of my dream was to become a <a href="https://www.eccouncil.org/Certification/certified-ethical-hacker">Certified Ethical Hacker</a> which is one of the best <a href="http://www.tomsitpro.com/articles/information-security-certifications,2-205.html">Information Technology Security Ceritifications</a> out there. Fortunately, i got a chance to take the C|EH course under <a href="https://my.linkedin.com/in/akaticonsulting">Mr.Krishna Rajagopal</a>.
        But unfortunately i haven't got the title yet since it is not that cheap. Although i am not yet certified as a C|EH, i have continued my researches and experiments. So i learnt more programming languages including <a href="https://en.wikipedia.org/wiki/Python_(programming_language)">Python</a>, <a href="https://en.wikipedia.org/wiki/Ruby_(programming_language)">Ruby</a> and most importantly <a href="https://en.wikipedia.org/wiki/Assembly_language">Assembly Language</a> and some web languages including <a href="https://en.wikipedia.org/wiki/XML">XML</a> and <a href="https://en.wikipedia.org/wiki/JavaScript">Javascript</a>. 
    </p>
    <p class="para">
        And then i resigned from my job and started working on Mobile App designing, specially in <a href="https://en.wikipedia.org/wiki/Android_software_development">Android</a> App Developing with the help of one of my best friends. But it didn't work well and then we started undestanding that we are on a Mobile app bubble and it is not that profitable without a good amount of initial investment for the marketing.
    </p>
    <p class="para">
        After some time, i joined to a company called <a href="http://www.vcnet.lk">VCNET</a> which was founded by one of my friends and i was incharge of whole technical department including programming, networking, web designing and information security. That was when i started to learn wed designing in deep. I am not that good at UI designing but i started learning <a href="https://en.wikipedia.org/wiki/HTML5">HTML5</a>, <a href="https://en.wikipedia.org/wiki/Cascading_Style_Sheets#CSS_3">CSS3</a>, <a href="https://en.wikipedia.org/wiki/Less_(stylesheet_language)">LESS</a>, <a href="https://en.wikipedia.org/wiki/Sass_(stylesheet_language)">SAAS</a>
        , <a href="https://en.wikipedia.org/wiki/JQuery">Jquery</a> and <a href="https://en.wikipedia.org/wiki/AngularJS">AngularJS</a>. Having knowledge in Information Security always tended me to concern about security of my codes when i do web or application programming.
    </p>
    <p class="para">
        As a suprise, i had an opportunity to work on a very entertaining field which is Game Developing. Acyually, Gaming was a main fact that i wanted to learn computer programming. i had a dream to develop games when i play games as a newbie to Computers. I thought this is the best time to learn game developing and one of my best friends influenced me to move into this field and i was learning <a href="https://en.wikipedia.org/wiki/C_Sharp_(programming_language)">C#</a> which is a prerequisite for <a href="https://unity3d.com/">Unity Game Engine</a>. I am looking forward to build some unique games since i have some great ideas in <a href="https://en.wikipedia.org/wiki/Massively_multiplayer_online_game">MMO (Massively Multiplayer Games)</a> model.
    </p>
    <p class="para">
        Currently i am working on some compression methods with the idea of finding an alternate concept for haffman encoding system.And Information Technology is not the only subject i spent my time on. I have also allocated some time for learning and following local and internationsl Politics, Economics, Neurology and last but not least Electronics.
    </p>
</article>